### PR TITLE
Support Rails 5

### PR DESCRIPTION
**Pull request by rrooding**
Nothing more to add, works as advertised :)

### CODE REVIEW

**Comment by avdgaag** [comment]
Well, let's :shipit: then :smile:

**Comment by bazzel** [comment]
Can't wait to see the new 0.6.0 release! ;)

**Comment by avdgaag** [comment]
Wait, what…? People actually use this? :smile:

**Comment by bazzel** [comment]
You started it...

**Comment by avdgaag** [comment]
> Can't wait to see the new 0.6.0 release! ;)

Done!

**Pull request merged**
